name: "issue-butler"

on: 
  issues:
    types: [opened]

jobs:
  manage_package:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: node test.js
