name: "issue-butler"

on: 
  issues:
    types: [opened]

jobs:
  manage_package:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: npm i @actions/core
    - run: npm i @actions/github
    - name: Run a one-line script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node test.js
