name: "issue-butler"

on: 
  issues:
    types: [opened]

jobs:
  manage_package:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - run: npm i @actions/core
    - run: npm i @actions/github
    - name: Run a one-line script
      env:
        INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node butler.js
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m 'manage_package'
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
